name: ar0ne
title: GSOC Devlog
description: About UI/UX improvements in Terasology!

gh_name: ar0ne
gh_commits: https://www.github.com/MovingBlocks/Terasology/commits/?author=ar0ne
gh_prs: https://github.com/MovingBlocks/Terasology/pulls?utf8=%E2%9C%93&q=is:pr+author:ar0ne
gh_issues: https://github.com/MovingBlocks/Terasology/issues?utf8=%E2%9C%93&q=is:issue+author:ar0ne
gh_project: https://www.github.com/MovingBlocks/Terasology

# -------------------------------------
# Build Settings
# -------------------------------------
markdown: kramdown
future: true
encodig: utf-8
highlighter: rouge